In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df_main = pd.read_csv(r'FINAL_BINARY_DATASET.csv')

In [3]:
target_mapping = {'No_Disease':0,
                  'Disease':1}
df_main['Target'] = df_main['Target'].map(target_mapping)

In [4]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6528 entries, 0 to 6527
Data columns (total 43 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Age of the patient                           6528 non-null   int64
 1   Blood pressure (mm/Hg)                       6528 non-null   int64
 2   Specific gravity of urine                    6528 non-null   float64
 3   Albumin in urine                             6528 non-null   int64
 4   Sugar in urine                               6528 non-null   int64
 5   Red blood cells in urine                     6528 non-null   int64
 6   Pus cells in urine                           6528 non-null   int64
 7   Pus cell clumps in urine                     6528 non-null   int64
 8   Bacteria in urine                            6528 non-null   int64
 9   Random blood glucose level (mg/dl)           6528 non-null   int64
 10  Blood urea (mg/dl)                           6528 non-null   float64
 11  Serum creatinine (mg/dl)                     6528 non-null   float64
 12  Sodium level (mEq/L)                         6528 non-null   float64
 13  Potassium level (mEq/L)                      6528 non-null   float64
 14  Hemoglobin level (gms)                       6528 non-null   float64
 15  Packed cell volume (%)                       6528 non-null   int64
 16  White blood cell count (cells/cumm)          6528 non-null   int64
 17  Red blood cell count (millions/cumm)         6528 non-null   float64
 18  Hypertension (yes/no)                        6528 non-null   int64
 19  Diabetes mellitus (yes/no)                   6528 non-null   int64
 20  Coronary artery disease (yes/no)             6528 non-null   int64
 21  Appetite (good/poor)                         6528 non-null   int64
 22  Pedal edema (yes/no)                         6528 non-null   int64
 23  Anemia (yes/no)                              6528 non-null   int64
 24  Estimated Glomerular Filtration Rate (eGFR)  6528 non-null   float64
 25  Urine protein-to-creatinine ratio            6528 non-null   float64
 26  Urine output (ml/day)                        6528 non-null   int64
 27  Serum albumin level                          6528 non-null   float64
 28  Cholesterol level                            6528 non-null   int64
 29  Parathyroid hormone (PTH) level              6528 non-null   float64
 30  Serum calcium level                          6528 non-null   float64
 31  Serum phosphate level                        6528 non-null   float64
 32  Family history of chronic kidney disease     6528 non-null   int64
 33  Smoking status                               6528 non-null   int64
 34  Body Mass Index (BMI)                        6528 non-null   float64
 35  Physical activity level                      6528 non-null   int64
 36  Duration of diabetes mellitus (years)        6528 non-null   int64
 37  Duration of hypertension (years)             6528 non-null   int64
 38  Cystatin C level                             6528 non-null   float64
 39  Urinary sediment microscopy results          6528 non-null   int64
 40  C-reactive protein (CRP) level               6528 non-null   float64
 41  Interleukin-6 (IL-6) level                   6528 non-null   float64
 42  Target                                       6528 non-null   int64
dtypes: float64(17), int64(26)
memory usage: 2.1 MB

In [5]:
df_main.head()

,Age of the patient,Blood pressure (mm/Hg),Specific gravity of urine,Albumin in urine,Sugar in urine,Red blood cells in urine,Pus cells in urine,Pus cell clumps in urine,Bacteria in urine,Random blood glucose level (mg/dl),...,Smoking status,Body Mass Index (BMI),Physical activity level,Duration of diabetes mellitus (years),Duration of hypertension (years),Cystatin C level,Urinary sediment microscopy results,C-reactive protein (CRP) level,Interleukin-6 (IL-6) level,Target
0,80,136,1.023,1,5,0,1,1,0,96,...,1,23.8,2,23,30,2.75,0,4.48,4.46,0
1,30,161,1.009,1,1,1,1,1,0,248,...,1,17.9,1,24,26,1.92,1,8.19,11.21,0
2,73,81,1.005,0,0,0,0,0,0,241,...,1,24.8,0,26,28,2.83,0,8.63,10.08,1
3,39,143,1.015,0,2,0,0,0,1,259,...,1,29.5,0,15,9,2.95,0,9.57,1.90,0
4,18,90,1.013,2,3,0,0,0,0,191,...,0,23.4,1,9,5,0.87,1,8.09,14.57,1

In [6]:
df_main.describe()

,Age of the patient,Blood pressure (mm/Hg),Specific gravity of urine,Albumin in urine,Sugar in urine,Red blood cells in urine,Pus cells in urine,Pus cell clumps in urine,Bacteria in urine,Random blood glucose level (mg/dl),...,Smoking status,Body Mass Index (BMI),Physical activity level,Duration of diabetes mellitus (years),Duration of hypertension (years),Cystatin C level,Urinary sediment microscopy results,C-reactive protein (CRP) level,Interleukin-6 (IL-6) level,Target
count,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,...,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000
mean,47.381434,130.607537,1.015008,2.521906,2.537377,0.488358,0.486366,0.505668,0.500153,284.366268,...,0.492800,27.543842,0.997396,15.035999,14.896293,1.739773,0.502604,5.059398,7.688843,0.463848
std,26.599563,30.890314,0.006137,1.780461,1.789474,0.499903,0.499852,0.500006,0.500038,131.581058,...,0.499986,7.682748,0.845228,9.490422,9.451162,0.765696,0.500032,3.020263,4.432348,0.498730
min,5.000000,80.000000,1.005000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,70.000000,...,0.000000,15.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.100000,0.500000,0.000000
25%,23.000000,103.000000,1.009000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,163.000000,...,0.000000,20.500000,0.000000,6.000000,6.000000,1.030000,0.000000,2.250000,3.670000,0.000000
50%,47.000000,131.000000,1.015000,3.000000,3.000000,0.000000,0.000000,1.000000,1.000000,283.000000,...,0.000000,27.600000,1.000000,15.000000,15.000000,1.730000,1.000000,5.100000,7.770000,0.000000
75%,72.000000,159.000000,1.021000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,404.000000,...,1.000000,34.600000,2.000000,24.000000,23.000000,2.450000,1.000000,7.810000,11.632500,1.000000
max,90.000000,180.000000,1.025000,5.000000,5.000000,1.000000,1.000000,1.000000,1.000000,500.000000,...,1.000000,40.000000,2.000000,30.000000,30.000000,3.000000,1.000000,10.000000,15.000000,1.000000

In [16]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier


selected_features = [
    'Age of the patient', 'Specific gravity of urine', 'Random blood glucose level (mg/dl)',
    'Blood urea (mg/dl)', 'Serum creatinine (mg/dl)', 'Sodium level (mEq/L)', 'Potassium level (mEq/L)',
    'Hemoglobin level (gms)',  'White blood cell count (cells/cumm)',
    'Red blood cell count (millions/cumm)', 'Estimated Glomerular Filtration Rate (eGFR)',
    'Urine protein-to-creatinine ratio', 'Urine output (ml/day)', 'Serum albumin level',
    'Parathyroid hormone (PTH) level', 'Serum calcium level', 'Duration of hypertension (years)',
    'Interleukin-6 (IL-6) level','Family history of chronic kidney disease','Serum phosphate level'
    ,'Pus cells in urine','Albumin in urine','Anemia (yes/no)'
]


df_main["Creatinine_eGFR_ratio"] = df_main["Serum creatinine (mg/dl)"] / df_main["Estimated Glomerular Filtration Rate (eGFR)"]

df_main["Age_hypertension_ratio"] = df_main["Age of the patient"] / (df_main["Duration of hypertension (years)"] + 1)
df_main["Serum_albumin_adjusted"] = df_main["Serum albumin level"] / (df_main["Urine output (ml/day)"] + 1)

df_main["total_blood_count"] = df_main["White blood cell count (cells/cumm)"] + df_main["Red blood cell count (millions/cumm)"]
df_main["electro_ratio"] = df_main["Sodium level (mEq/L)"] * df_main["Potassium level (mEq/L)"] **2
df_main["blood_creatinine_ratio"] = df_main["Blood urea (mg/dl)"] / df_main["Serum creatinine (mg/dl)"] 

df_main["Creatinine_eGFR_ratio"] = df_main["Serum creatinine (mg/dl)"] / df_main["Estimated Glomerular Filtration Rate (eGFR)"]
df_main["Age_hypertension_ratio"] = df_main["Age of the patient"] / (df_main["Duration of hypertension (years)"] + 1)
df_main["Serum_albumin_adjusted"] = df_main["Serum albumin level"] / (df_main["Urine output (ml/day)"] + 1)
df_main["total_blood_count"] = df_main["White blood cell count (cells/cumm)"] + df_main["Red blood cell count (millions/cumm)"]

df_main["blood_creatinine_ratio"] = df_main["Blood urea (mg/dl)"] / df_main["Serum creatinine (mg/dl)"]

df_main["eGFR_flag"] = (df_main["Estimated Glomerular Filtration Rate (eGFR)"] < 60).astype(int)
df_main["albumin_stress_index"] = df_main["Albumin in urine"] / (df_main["Serum creatinine (mg/dl)"] + 1)
df_main["hypertension_burden"] = df_main["Duration of hypertension (years)"] / (df_main["Age of the patient"] + 1)

df_main["electrolyte_imbalance"] = abs(df_main["Sodium level (mEq/L)"] - df_main["Potassium level (mEq/L)"])
df_main["blood_toxicity_score"] = df_main["Blood urea (mg/dl)"] * 0.6 + df_main["Serum creatinine (mg/dl)"] * 0.4

df_main["inflammation_ratio"] = df_main["Interleukin-6 (IL-6) level"] / (df_main["Serum albumin level"] + 1)


selected_features += [
    'Creatinine_eGFR_ratio', 'Age_hypertension_ratio', 'Serum_albumin_adjusted',
    'total_blood_count',  'blood_creatinine_ratio',
    'eGFR_flag', 'albumin_stress_index', 'hypertension_burden',
    'electrolyte_imbalance', 'blood_toxicity_score',
    'inflammation_ratio'
]



X = df_main[selected_features]
y = df_main["Target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC(),
    "KNN": KNeighborsClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric="logloss"),
    "LightGBM": LGBMClassifier(),
    "CatBoost": CatBoostClassifier(verbose=0)
}


for name, model in models.items():
    print(f"\n Evaluating: {name}")
    
    if name in ["Logistic Regression", "SVM", "KNN"]:
        model.fit(X_train_scaled, y_train)
        preds = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
    
    print(classification_report(y_test, preds))

 Evaluating: Logistic Regression
              precision    recall  f1-score   support

           0       0.66      0.70      0.68       700
           1       0.63      0.57      0.60       606

    accuracy                           0.64      1306
   macro avg       0.64      0.64      0.64      1306
weighted avg       0.64      0.64      0.64      1306


 Evaluating: Decision Tree
              precision    recall  f1-score   support

           0       0.62      0.59      0.60       700
           1       0.55      0.58      0.56       606

    accuracy                           0.58      1306
   macro avg       0.58      0.58      0.58      1306
weighted avg       0.59      0.58      0.59      1306


 Evaluating: Random Forest
              precision    recall  f1-score   support

           0       0.69      0.82      0.75       700
           1       0.73      0.57      0.64       606

    accuracy                           0.71      1306
   macro avg       0.71      0.70      0.70      1306
weighted avg       0.71      0.71      0.70      1306


 Evaluating: SVM
              precision    recall  f1-score   support

           0       0.75      0.83      0.79       700
           1       0.78      0.69      0.73       606

    accuracy                           0.76      1306
   macro avg       0.77      0.76      0.76      1306
weighted avg       0.77      0.76      0.76      1306


 Evaluating: KNN
              precision    recall  f1-score   support

           0       0.69      0.35      0.47       700
           1       0.52      0.82      0.64       606

    accuracy                           0.57      1306
   macro avg       0.61      0.58      0.55      1306
weighted avg       0.61      0.57      0.55      1306


 Evaluating: AdaBoost
              precision    recall  f1-score   support

           0       0.75      0.77      0.76       700
           1       0.72      0.70      0.71       606

    accuracy                           0.74      1306
   macro avg       0.74      0.73      0.74      1306
weighted avg       0.74      0.74      0.74      1306


 Evaluating: Gradient Boosting
              precision    recall  f1-score   support

           0       0.72      0.79      0.76       700
           1       0.73      0.65      0.69       606

    accuracy                           0.73      1306
   macro avg       0.73      0.72      0.72      1306
weighted avg       0.73      0.73      0.73      1306


 Evaluating: XGBoost
              precision    recall  f1-score   support

           0       0.75      0.77      0.76       700
           1       0.72      0.70      0.71       606

    accuracy                           0.74      1306
   macro avg       0.73      0.73      0.73      1306
weighted avg       0.73      0.74      0.73      1306


 Evaluating: LightGBM
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 2422, number of negative: 2800
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000697 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6368
[LightGBM] [Info] Number of data points in the train set: 5222, number of used features: 34
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.463807 -> initscore=-0.145026
[LightGBM] [Info] Start training from score -0.145026
              precision    recall  f1-score   support

           0       0.74      0.81      0.77       700
           1       0.75      0.67      0.71       606

    accuracy                           0.74      1306
   macro avg       0.75      0.74      0.74      1306
weighted avg       0.74      0.74      0.74      1306


 Evaluating: CatBoost
              precision    recall  f1-score   support

           0       0.76      0.83      0.79       700
           1       0.78      0.70      0.74       606

    accuracy                           0.77      1306
   macro avg       0.77      0.76      0.76      1306
weighted avg       0.77      0.77      0.77      1306

In [17]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1306 entries, 3917 to 650
Data columns (total 34 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Age of the patient                           1306 non-null   int64
 1   Specific gravity of urine                    1306 non-null   float64
 2   Random blood glucose level (mg/dl)           1306 non-null   int64
 3   Blood urea (mg/dl)                           1306 non-null   float64
 4   Serum creatinine (mg/dl)                     1306 non-null   float64
 5   Sodium level (mEq/L)                         1306 non-null   float64
 6   Potassium level (mEq/L)                      1306 non-null   float64
 7   Hemoglobin level (gms)                       1306 non-null   float64
 8   White blood cell count (cells/cumm)          1306 non-null   int64
 9   Red blood cell count (millions/cumm)         1306 non-null   float64
 10  Estimated Glomerular Filtration Rate (eGFR)  1306 non-null   float64
 11  Urine protein-to-creatinine ratio            1306 non-null   float64
 12  Urine output (ml/day)                        1306 non-null   int64
 13  Serum albumin level                          1306 non-null   float64
 14  Parathyroid hormone (PTH) level              1306 non-null   float64
 15  Serum calcium level                          1306 non-null   float64
 16  Duration of hypertension (years)             1306 non-null   int64
 17  Interleukin-6 (IL-6) level                   1306 non-null   float64
 18  Family history of chronic kidney disease     1306 non-null   int64
 19  Serum phosphate level                        1306 non-null   float64
 20  Pus cells in urine                           1306 non-null   int64
 21  Albumin in urine                             1306 non-null   int64
 22  Anemia (yes/no)                              1306 non-null   int64
 23  Creatinine_eGFR_ratio                        1306 non-null   float64
 24  Age_hypertension_ratio                       1306 non-null   float64
 25  Serum_albumin_adjusted                       1306 non-null   float64
 26  total_blood_count                            1306 non-null   float64
 27  blood_creatinine_ratio                       1306 non-null   float64
 28  eGFR_flag                                    1306 non-null   int32
 29  albumin_stress_index                         1306 non-null   float64
 30  hypertension_burden                          1306 non-null   float64
 31  electrolyte_imbalance                        1306 non-null   float64
 32  blood_toxicity_score                         1306 non-null   float64
 33  inflammation_ratio                           1306 non-null   float64
dtypes: float64(24), int32(1), int64(9)
memory usage: 352.0 KB

In [18]:
X_test.iloc[2]

Age of the patient                                 6.000000
Specific gravity of urine                          1.018000
Random blood glucose level (mg/dl)               465.000000
Blood urea (mg/dl)                                60.040280
Serum creatinine (mg/dl)                           6.550000
Sodium level (mEq/L)                             120.423406
Potassium level (mEq/L)                            4.487789
Hemoglobin level (gms)                            10.100000
White blood cell count (cells/cumm)            12323.000000
Red blood cell count (millions/cumm)               3.700000
Estimated Glomerular Filtration Rate (eGFR)       68.460000
Urine protein-to-creatinine ratio                  0.830000
Urine output (ml/day)                           1373.000000
Serum albumin level                                4.430000
Parathyroid hormone (PTH) level                   68.261093
Serum calcium level                                7.700000
Duration of hypertension (years)                  20.000000
Interleukin-6 (IL-6) level                         4.130000
Family history of chronic kidney disease           1.000000
Serum phosphate level                              4.360000
Pus cells in urine                                 0.000000
Albumin in urine                                   1.000000
Anemia (yes/no)                                    1.000000
Creatinine_eGFR_ratio                              0.095676
Age_hypertension_ratio                             0.285714
Serum_albumin_adjusted                             0.003224
total_blood_count                              12326.700000
blood_creatinine_ratio                             9.166455
eGFR_flag                                          0.000000
albumin_stress_index                               0.132450
hypertension_burden                                2.857143
electrolyte_imbalance                            115.935617
blood_toxicity_score                              38.644168
inflammation_ratio                                 0.760589
Name: 2826, dtype: float64

In [19]:
y_train.iloc[2826]

1

In [20]:
from catboost import CatBoostClassifier
import joblib

model = CatBoostClassifier()
model.fit(X_train, y_train)


joblib.dump(model, "catboost_model_updated_Final.joblib")

Learning rate set to 0.020867
0:	learn: 0.6910848	total: 7.33ms	remaining: 7.32s
1:	learn: 0.6889342	total: 13.3ms	remaining: 6.64s
2:	learn: 0.6866957	total: 19.7ms	remaining: 6.54s
3:	learn: 0.6846053	total: 25.9ms	remaining: 6.45s
4:	learn: 0.6826428	total: 31.9ms	remaining: 6.34s
5:	learn: 0.6806942	total: 38ms	remaining: 6.3s
6:	learn: 0.6789324	total: 43.5ms	remaining: 6.17s
7:	learn: 0.6770171	total: 49ms	remaining: 6.08s
8:	learn: 0.6752781	total: 54.3ms	remaining: 5.98s
9:	learn: 0.6737562	total: 59.8ms	remaining: 5.92s
10:	learn: 0.6720503	total: 65.5ms	remaining: 5.88s
11:	learn: 0.6705775	total: 71.7ms	remaining: 5.9s
12:	learn: 0.6688814	total: 77.2ms	remaining: 5.86s
13:	learn: 0.6674085	total: 82.6ms	remaining: 5.82s
14:	learn: 0.6660528	total: 88.1ms	remaining: 5.78s
15:	learn: 0.6645427	total: 93.4ms	remaining: 5.74s
16:	learn: 0.6630822	total: 98.7ms	remaining: 5.71s
17:	learn: 0.6615805	total: 104ms	remaining: 5.68s
18:	learn: 0.6602165	total: 110ms	remaining: 5.66s
19:	learn: 0.6586516	total: 115ms	remaining: 5.62s
20:	learn: 0.6571232	total: 120ms	remaining: 5.6s
21:	learn: 0.6555891	total: 125ms	remaining: 5.58s
22:	learn: 0.6541295	total: 131ms	remaining: 5.55s
23:	learn: 0.6526289	total: 136ms	remaining: 5.54s
24:	learn: 0.6511473	total: 145ms	remaining: 5.67s
25:	learn: 0.6499661	total: 155ms	remaining: 5.81s
26:	learn: 0.6488457	total: 164ms	remaining: 5.91s
27:	learn: 0.6476114	total: 170ms	remaining: 5.91s
28:	learn: 0.6463319	total: 176ms	remaining: 5.91s
29:	learn: 0.6451518	total: 182ms	remaining: 5.88s
30:	learn: 0.6439196	total: 187ms	remaining: 5.85s
31:	learn: 0.6426546	total: 193ms	remaining: 5.84s
32:	learn: 0.6417138	total: 199ms	remaining: 5.83s
33:	learn: 0.6407505	total: 204ms	remaining: 5.8s
34:	learn: 0.6396497	total: 210ms	remaining: 5.8s
35:	learn: 0.6383323	total: 216ms	remaining: 5.79s
36:	learn: 0.6372227	total: 223ms	remaining: 5.79s
37:	learn: 0.6360447	total: 228ms	remaining: 5.78s
38:	learn: 0.6349225	total: 234ms	remaining: 5.77s
39:	learn: 0.6338535	total: 240ms	remaining: 5.76s
40:	learn: 0.6327561	total: 246ms	remaining: 5.75s
41:	learn: 0.6315939	total: 252ms	remaining: 5.74s
42:	learn: 0.6306049	total: 256ms	remaining: 5.71s
43:	learn: 0.6296134	total: 262ms	remaining: 5.68s
44:	learn: 0.6285220	total: 267ms	remaining: 5.66s
45:	learn: 0.6275733	total: 272ms	remaining: 5.63s
46:	learn: 0.6266702	total: 277ms	remaining: 5.61s
47:	learn: 0.6256010	total: 282ms	remaining: 5.59s
48:	learn: 0.6246536	total: 287ms	remaining: 5.58s
49:	learn: 0.6237249	total: 293ms	remaining: 5.56s
50:	learn: 0.6228781	total: 298ms	remaining: 5.54s
51:	learn: 0.6219007	total: 303ms	remaining: 5.52s
52:	learn: 0.6209498	total: 308ms	remaining: 5.5s
53:	learn: 0.6200514	total: 313ms	remaining: 5.48s
54:	learn: 0.6191403	total: 318ms	remaining: 5.46s
55:	learn: 0.6182722	total: 323ms	remaining: 5.44s
56:	learn: 0.6173409	total: 327ms	remaining: 5.41s
57:	learn: 0.6164933	total: 332ms	remaining: 5.39s
58:	learn: 0.6156678	total: 337ms	remaining: 5.37s
59:	learn: 0.6149111	total: 342ms	remaining: 5.36s
60:	learn: 0.6140346	total: 347ms	remaining: 5.34s
61:	learn: 0.6130460	total: 351ms	remaining: 5.32s
62:	learn: 0.6122557	total: 356ms	remaining: 5.3s
63:	learn: 0.6113922	total: 361ms	remaining: 5.28s
64:	learn: 0.6106406	total: 366ms	remaining: 5.26s
65:	learn: 0.6097868	total: 370ms	remaining: 5.24s
66:	learn: 0.6089572	total: 375ms	remaining: 5.22s
67:	learn: 0.6082128	total: 380ms	remaining: 5.2s
68:	learn: 0.6073430	total: 384ms	remaining: 5.18s
69:	learn: 0.6065033	total: 389ms	remaining: 5.17s
70:	learn: 0.6057118	total: 394ms	remaining: 5.15s
71:	learn: 0.6047991	total: 399ms	remaining: 5.14s
72:	learn: 0.6041051	total: 405ms	remaining: 5.14s
73:	learn: 0.6033861	total: 411ms	remaining: 5.14s
74:	learn: 0.6025031	total: 417ms	remaining: 5.14s
75:	learn: 0.6016767	total: 422ms	remaining: 5.13s
76:	learn: 0.6009102	total: 427ms	remaining: 5.11s
77:	learn: 0.6000818	total: 432ms	remaining: 5.11s
78:	learn: 0.5993246	total: 437ms	remaining: 5.09s
79:	learn: 0.5985869	total: 441ms	remaining: 5.08s
80:	learn: 0.5978779	total: 446ms	remaining: 5.06s
81:	learn: 0.5970092	total: 451ms	remaining: 5.05s
82:	learn: 0.5962837	total: 456ms	remaining: 5.04s
83:	learn: 0.5955801	total: 461ms	remaining: 5.02s
84:	learn: 0.5948276	total: 466ms	remaining: 5.01s
85:	learn: 0.5940552	total: 470ms	remaining: 5s
86:	learn: 0.5932267	total: 475ms	remaining: 4.98s
87:	learn: 0.5924023	total: 480ms	remaining: 4.97s
88:	learn: 0.5915589	total: 485ms	remaining: 4.96s
89:	learn: 0.5908072	total: 489ms	remaining: 4.95s
90:	learn: 0.5900700	total: 494ms	remaining: 4.93s
91:	learn: 0.5893914	total: 499ms	remaining: 4.92s
92:	learn: 0.5885602	total: 503ms	remaining: 4.91s
93:	learn: 0.5878439	total: 508ms	remaining: 4.9s
94:	learn: 0.5872047	total: 513ms	remaining: 4.89s
95:	learn: 0.5864460	total: 518ms	remaining: 4.87s
96:	learn: 0.5857000	total: 522ms	remaining: 4.86s
97:	learn: 0.5850307	total: 527ms	remaining: 4.85s
98:	learn: 0.5842690	total: 531ms	remaining: 4.83s
99:	learn: 0.5835895	total: 536ms	remaining: 4.82s
100:	learn: 0.5827837	total: 541ms	remaining: 4.81s
101:	learn: 0.5821290	total: 546ms	remaining: 4.8s
102:	learn: 0.5814695	total: 550ms	remaining: 4.79s
103:	learn: 0.5808769	total: 555ms	remaining: 4.78s
104:	learn: 0.5802388	total: 560ms	remaining: 4.78s
105:	learn: 0.5795309	total: 565ms	remaining: 4.77s
106:	learn: 0.5788713	total: 571ms	remaining: 4.76s
107:	learn: 0.5782463	total: 576ms	remaining: 4.75s
108:	learn: 0.5775361	total: 581ms	remaining: 4.75s
109:	learn: 0.5768872	total: 586ms	remaining: 4.74s
110:	learn: 0.5762150	total: 591ms	remaining: 4.73s
111:	learn: 0.5754156	total: 596ms	remaining: 4.72s
112:	learn: 0.5746754	total: 600ms	remaining: 4.71s
113:	learn: 0.5740642	total: 605ms	remaining: 4.7s
114:	learn: 0.5735077	total: 610ms	remaining: 4.69s
115:	learn: 0.5729844	total: 614ms	remaining: 4.68s
116:	learn: 0.5723440	total: 620ms	remaining: 4.68s
117:	learn: 0.5717688	total: 625ms	remaining: 4.67s
118:	learn: 0.5711650	total: 631ms	remaining: 4.67s
119:	learn: 0.5705118	total: 636ms	remaining: 4.67s
120:	learn: 0.5699884	total: 642ms	remaining: 4.66s
121:	learn: 0.5694628	total: 647ms	remaining: 4.66s
122:	learn: 0.5688579	total: 652ms	remaining: 4.65s
123:	learn: 0.5681764	total: 657ms	remaining: 4.64s
124:	learn: 0.5674864	total: 662ms	remaining: 4.64s
125:	learn: 0.5669065	total: 667ms	remaining: 4.63s
126:	learn: 0.5663365	total: 672ms	remaining: 4.62s
127:	learn: 0.5656214	total: 676ms	remaining: 4.61s
128:	learn: 0.5649992	total: 681ms	remaining: 4.6s
129:	learn: 0.5644049	total: 686ms	remaining: 4.59s
130:	learn: 0.5636638	total: 691ms	remaining: 4.58s
131:	learn: 0.5630496	total: 696ms	remaining: 4.58s
132:	learn: 0.5624901	total: 701ms	remaining: 4.57s
133:	learn: 0.5618620	total: 706ms	remaining: 4.56s
134:	learn: 0.5613164	total: 710ms	remaining: 4.55s
135:	learn: 0.5608358	total: 715ms	remaining: 4.54s
136:	learn: 0.5602466	total: 720ms	remaining: 4.53s
137:	learn: 0.5595772	total: 725ms	remaining: 4.53s
138:	learn: 0.5589433	total: 730ms	remaining: 4.52s
139:	learn: 0.5584016	total: 734ms	remaining: 4.51s
140:	learn: 0.5578053	total: 739ms	remaining: 4.5s
141:	learn: 0.5571896	total: 745ms	remaining: 4.5s
142:	learn: 0.5565214	total: 750ms	remaining: 4.49s
143:	learn: 0.5558931	total: 756ms	remaining: 4.49s
144:	learn: 0.5553043	total: 761ms	remaining: 4.49s
145:	learn: 0.5546935	total: 766ms	remaining: 4.48s
146:	learn: 0.5541139	total: 772ms	remaining: 4.48s
147:	learn: 0.5536052	total: 777ms	remaining: 4.47s
148:	learn: 0.5530262	total: 783ms	remaining: 4.47s
149:	learn: 0.5525377	total: 788ms	remaining: 4.46s
150:	learn: 0.5519872	total: 793ms	remaining: 4.46s
151:	learn: 0.5513522	total: 798ms	remaining: 4.45s
152:	learn: 0.5508034	total: 804ms	remaining: 4.45s
153:	learn: 0.5501721	total: 809ms	remaining: 4.44s
154:	learn: 0.5496118	total: 814ms	remaining: 4.44s
155:	learn: 0.5491283	total: 819ms	remaining: 4.43s
156:	learn: 0.5485957	total: 825ms	remaining: 4.43s
157:	learn: 0.5480516	total: 831ms	remaining: 4.43s
158:	learn: 0.5475840	total: 836ms	remaining: 4.42s
159:	learn: 0.5470313	total: 842ms	remaining: 4.42s
160:	learn: 0.5464946	total: 848ms	remaining: 4.42s
161:	learn: 0.5460148	total: 854ms	remaining: 4.42s
162:	learn: 0.5453753	total: 859ms	remaining: 4.41s
163:	learn: 0.5447726	total: 864ms	remaining: 4.41s
164:	learn: 0.5442827	total: 870ms	remaining: 4.4s
165:	learn: 0.5437484	total: 875ms	remaining: 4.4s
166:	learn: 0.5432071	total: 880ms	remaining: 4.39s
167:	learn: 0.5427110	total: 885ms	remaining: 4.38s
168:	learn: 0.5422273	total: 890ms	remaining: 4.38s
169:	learn: 0.5417247	total: 896ms	remaining: 4.37s
170:	learn: 0.5411377	total: 901ms	remaining: 4.37s
171:	learn: 0.5407270	total: 907ms	remaining: 4.37s
172:	learn: 0.5402052	total: 912ms	remaining: 4.36s
173:	learn: 0.5396195	total: 918ms	remaining: 4.36s
174:	learn: 0.5391444	total: 925ms	remaining: 4.36s
175:	learn: 0.5385866	total: 930ms	remaining: 4.35s
176:	learn: 0.5380508	total: 936ms	remaining: 4.35s
177:	learn: 0.5375708	total: 941ms	remaining: 4.35s
178:	learn: 0.5370615	total: 947ms	remaining: 4.34s
179:	learn: 0.5366138	total: 952ms	remaining: 4.34s
180:	learn: 0.5361338	total: 957ms	remaining: 4.33s
181:	learn: 0.5355817	total: 963ms	remaining: 4.33s
182:	learn: 0.5352164	total: 968ms	remaining: 4.32s
183:	learn: 0.5347082	total: 973ms	remaining: 4.32s
184:	learn: 0.5341918	total: 978ms	remaining: 4.31s
185:	learn: 0.5337190	total: 984ms	remaining: 4.31s
186:	learn: 0.5331604	total: 989ms	remaining: 4.3s
187:	learn: 0.5326271	total: 994ms	remaining: 4.29s
188:	learn: 0.5321305	total: 999ms	remaining: 4.29s
189:	learn: 0.5315446	total: 1s	remaining: 4.28s
190:	learn: 0.5310493	total: 1.01s	remaining: 4.28s
191:	learn: 0.5305771	total: 1.01s	remaining: 4.27s
192:	learn: 0.5300399	total: 1.02s	remaining: 4.27s
193:	learn: 0.5295384	total: 1.03s	remaining: 4.27s
194:	learn: 0.5290107	total: 1.03s	remaining: 4.26s
195:	learn: 0.5285091	total: 1.04s	remaining: 4.25s
196:	learn: 0.5279731	total: 1.04s	remaining: 4.25s
197:	learn: 0.5275474	total: 1.05s	remaining: 4.24s
198:	learn: 0.5270577	total: 1.05s	remaining: 4.23s
199:	learn: 0.5265530	total: 1.06s	remaining: 4.23s
200:	learn: 0.5260312	total: 1.06s	remaining: 4.22s
201:	learn: 0.5255202	total: 1.07s	remaining: 4.22s
202:	learn: 0.5250164	total: 1.07s	remaining: 4.21s
203:	learn: 0.5244472	total: 1.08s	remaining: 4.21s
204:	learn: 0.5239520	total: 1.08s	remaining: 4.2s
205:	learn: 0.5235949	total: 1.09s	remaining: 4.2s
206:	learn: 0.5231948	total: 1.09s	remaining: 4.19s
207:	learn: 0.5227034	total: 1.1s	remaining: 4.18s
208:	learn: 0.5222323	total: 1.1s	remaining: 4.18s
209:	learn: 0.5217389	total: 1.11s	remaining: 4.17s
210:	learn: 0.5212065	total: 1.11s	remaining: 4.17s
211:	learn: 0.5206515	total: 1.12s	remaining: 4.16s
212:	learn: 0.5200954	total: 1.13s	remaining: 4.16s
213:	learn: 0.5195963	total: 1.13s	remaining: 4.16s
214:	learn: 0.5191008	total: 1.14s	remaining: 4.15s
215:	learn: 0.5187432	total: 1.14s	remaining: 4.15s
216:	learn: 0.5183288	total: 1.15s	remaining: 4.14s
217:	learn: 0.5178567	total: 1.15s	remaining: 4.14s
218:	learn: 0.5174758	total: 1.16s	remaining: 4.13s
219:	learn: 0.5170143	total: 1.16s	remaining: 4.13s
220:	learn: 0.5165864	total: 1.17s	remaining: 4.12s
221:	learn: 0.5161908	total: 1.17s	remaining: 4.12s
222:	learn: 0.5157450	total: 1.18s	remaining: 4.11s
223:	learn: 0.5152465	total: 1.19s	remaining: 4.11s
224:	learn: 0.5148207	total: 1.19s	remaining: 4.1s
225:	learn: 0.5144440	total: 1.2s	remaining: 4.1s
226:	learn: 0.5140133	total: 1.2s	remaining: 4.09s
227:	learn: 0.5136499	total: 1.21s	remaining: 4.09s
228:	learn: 0.5132219	total: 1.21s	remaining: 4.08s
229:	learn: 0.5127590	total: 1.22s	remaining: 4.08s
230:	learn: 0.5123080	total: 1.22s	remaining: 4.08s
231:	learn: 0.5118811	total: 1.23s	remaining: 4.07s
232:	learn: 0.5115047	total: 1.24s	remaining: 4.07s
233:	learn: 0.5110318	total: 1.24s	remaining: 4.06s
234:	learn: 0.5106338	total: 1.25s	remaining: 4.05s
235:	learn: 0.5101853	total: 1.25s	remaining: 4.05s
236:	learn: 0.5096243	total: 1.25s	remaining: 4.04s
237:	learn: 0.5092576	total: 1.26s	remaining: 4.04s
238:	learn: 0.5087199	total: 1.26s	remaining: 4.03s
239:	learn: 0.5083120	total: 1.27s	remaining: 4.02s
240:	learn: 0.5078603	total: 1.27s	remaining: 4.01s
241:	learn: 0.5074407	total: 1.28s	remaining: 4.01s
242:	learn: 0.5070523	total: 1.28s	remaining: 4s
243:	learn: 0.5066239	total: 1.29s	remaining: 3.99s
244:	learn: 0.5062665	total: 1.29s	remaining: 3.99s
245:	learn: 0.5059276	total: 1.3s	remaining: 3.98s
246:	learn: 0.5053696	total: 1.3s	remaining: 3.98s
247:	learn: 0.5049071	total: 1.31s	remaining: 3.97s
248:	learn: 0.5045015	total: 1.31s	remaining: 3.96s
249:	learn: 0.5040316	total: 1.32s	remaining: 3.96s
250:	learn: 0.5035703	total: 1.32s	remaining: 3.95s
251:	learn: 0.5030714	total: 1.33s	remaining: 3.94s
252:	learn: 0.5026764	total: 1.33s	remaining: 3.94s
253:	learn: 0.5023201	total: 1.34s	remaining: 3.93s
254:	learn: 0.5019763	total: 1.34s	remaining: 3.93s
255:	learn: 0.5014500	total: 1.35s	remaining: 3.92s
256:	learn: 0.5010098	total: 1.35s	remaining: 3.92s
257:	learn: 0.5005892	total: 1.36s	remaining: 3.91s
258:	learn: 0.5001383	total: 1.36s	remaining: 3.9s
259:	learn: 0.4998077	total: 1.37s	remaining: 3.9s
260:	learn: 0.4993707	total: 1.38s	remaining: 3.9s
261:	learn: 0.4989202	total: 1.38s	remaining: 3.89s
262:	learn: 0.4984859	total: 1.39s	remaining: 3.89s
263:	learn: 0.4980306	total: 1.39s	remaining: 3.88s
264:	learn: 0.4976039	total: 1.4s	remaining: 3.88s
265:	learn: 0.4970883	total: 1.4s	remaining: 3.88s
266:	learn: 0.4966887	total: 1.41s	remaining: 3.87s
267:	learn: 0.4962870	total: 1.42s	remaining: 3.87s
268:	learn: 0.4958181	total: 1.42s	remaining: 3.86s
269:	learn: 0.4954490	total: 1.43s	remaining: 3.86s
270:	learn: 0.4950308	total: 1.43s	remaining: 3.85s
271:	learn: 0.4946254	total: 1.44s	remaining: 3.85s
272:	learn: 0.4943569	total: 1.44s	remaining: 3.85s
273:	learn: 0.4939536	total: 1.45s	remaining: 3.84s
274:	learn: 0.4935071	total: 1.45s	remaining: 3.83s
275:	learn: 0.4931176	total: 1.46s	remaining: 3.83s
276:	learn: 0.4926551	total: 1.47s	remaining: 3.83s
277:	learn: 0.4922394	total: 1.47s	remaining: 3.82s
278:	learn: 0.4918838	total: 1.48s	remaining: 3.81s
279:	learn: 0.4915160	total: 1.48s	remaining: 3.81s
280:	learn: 0.4911136	total: 1.49s	remaining: 3.8s
281:	learn: 0.4906994	total: 1.49s	remaining: 3.8s
282:	learn: 0.4903219	total: 1.5s	remaining: 3.79s
283:	learn: 0.4899692	total: 1.5s	remaining: 3.78s
284:	learn: 0.4895744	total: 1.5s	remaining: 3.78s
285:	learn: 0.4892014	total: 1.51s	remaining: 3.77s
286:	learn: 0.4888266	total: 1.51s	remaining: 3.76s
287:	learn: 0.4883703	total: 1.52s	remaining: 3.76s
288:	learn: 0.4880143	total: 1.52s	remaining: 3.75s
289:	learn: 0.4875197	total: 1.53s	remaining: 3.75s
290:	learn: 0.4871090	total: 1.54s	remaining: 3.74s
291:	learn: 0.4867445	total: 1.54s	remaining: 3.74s
292:	learn: 0.4863191	total: 1.55s	remaining: 3.73s
293:	learn: 0.4858898	total: 1.55s	remaining: 3.73s
294:	learn: 0.4854726	total: 1.56s	remaining: 3.72s
295:	learn: 0.4851007	total: 1.56s	remaining: 3.72s
296:	learn: 0.4847020	total: 1.57s	remaining: 3.71s
297:	learn: 0.4843617	total: 1.57s	remaining: 3.71s
298:	learn: 0.4838510	total: 1.58s	remaining: 3.7s
299:	learn: 0.4834724	total: 1.58s	remaining: 3.7s
300:	learn: 0.4831796	total: 1.59s	remaining: 3.69s
301:	learn: 0.4827129	total: 1.6s	remaining: 3.69s
302:	learn: 0.4823815	total: 1.6s	remaining: 3.68s
303:	learn: 0.4819872	total: 1.61s	remaining: 3.68s
304:	learn: 0.4816354	total: 1.61s	remaining: 3.67s
305:	learn: 0.4812769	total: 1.62s	remaining: 3.67s
306:	learn: 0.4808871	total: 1.62s	remaining: 3.66s
307:	learn: 0.4805671	total: 1.63s	remaining: 3.66s
308:	learn: 0.4802080	total: 1.63s	remaining: 3.65s
309:	learn: 0.4798487	total: 1.64s	remaining: 3.65s
310:	learn: 0.4795784	total: 1.65s	remaining: 3.64s
311:	learn: 0.4791120	total: 1.65s	remaining: 3.64s
312:	learn: 0.4787512	total: 1.66s	remaining: 3.63s
313:	learn: 0.4783192	total: 1.66s	remaining: 3.63s
314:	learn: 0.4779184	total: 1.67s	remaining: 3.62s
315:	learn: 0.4775180	total: 1.67s	remaining: 3.62s
316:	learn: 0.4770457	total: 1.68s	remaining: 3.61s
317:	learn: 0.4766562	total: 1.68s	remaining: 3.6s
318:	learn: 0.4763363	total: 1.69s	remaining: 3.6s
319:	learn: 0.4759794	total: 1.69s	remaining: 3.59s
320:	learn: 0.4756025	total: 1.7s	remaining: 3.59s
321:	learn: 0.4752572	total: 1.7s	remaining: 3.58s
322:	learn: 0.4748812	total: 1.71s	remaining: 3.57s
323:	learn: 0.4745475	total: 1.71s	remaining: 3.57s
324:	learn: 0.4742461	total: 1.72s	remaining: 3.56s
325:	learn: 0.4737986	total: 1.72s	remaining: 3.56s
326:	learn: 0.4733811	total: 1.73s	remaining: 3.55s
327:	learn: 0.4730045	total: 1.73s	remaining: 3.54s
328:	learn: 0.4726381	total: 1.73s	remaining: 3.54s
329:	learn: 0.4722738	total: 1.74s	remaining: 3.53s
330:	learn: 0.4719566	total: 1.74s	remaining: 3.52s
331:	learn: 0.4715897	total: 1.75s	remaining: 3.52s
332:	learn: 0.4712242	total: 1.75s	remaining: 3.51s
333:	learn: 0.4709072	total: 1.76s	remaining: 3.5s
334:	learn: 0.4705131	total: 1.76s	remaining: 3.5s
335:	learn: 0.4701282	total: 1.77s	remaining: 3.49s
336:	learn: 0.4697482	total: 1.77s	remaining: 3.49s
337:	learn: 0.4693694	total: 1.78s	remaining: 3.48s
338:	learn: 0.4689835	total: 1.78s	remaining: 3.48s
339:	learn: 0.4686415	total: 1.79s	remaining: 3.48s
340:	learn: 0.4682620	total: 1.8s	remaining: 3.47s
341:	learn: 0.4679705	total: 1.8s	remaining: 3.47s
342:	learn: 0.4676290	total: 1.81s	remaining: 3.46s
343:	learn: 0.4672126	total: 1.81s	remaining: 3.46s
344:	learn: 0.4668646	total: 1.82s	remaining: 3.46s
345:	learn: 0.4665071	total: 1.83s	remaining: 3.45s
346:	learn: 0.4660897	total: 1.85s	remaining: 3.48s
347:	learn: 0.4657442	total: 1.87s	remaining: 3.5s
348:	learn: 0.4653708	total: 1.88s	remaining: 3.51s
349:	learn: 0.4650217	total: 1.89s	remaining: 3.51s
350:	learn: 0.4645955	total: 1.9s	remaining: 3.51s
351:	learn: 0.4642237	total: 1.9s	remaining: 3.51s
352:	learn: 0.4638993	total: 1.91s	remaining: 3.5s
353:	learn: 0.4635959	total: 1.92s	remaining: 3.5s
354:	learn: 0.4631620	total: 1.93s	remaining: 3.5s
355:	learn: 0.4627792	total: 1.93s	remaining: 3.49s
356:	learn: 0.4624405	total: 1.94s	remaining: 3.49s
357:	learn: 0.4620643	total: 1.94s	remaining: 3.48s
358:	learn: 0.4617083	total: 1.95s	remaining: 3.48s
359:	learn: 0.4612877	total: 1.95s	remaining: 3.47s
360:	learn: 0.4609053	total: 1.96s	remaining: 3.46s
361:	learn: 0.4605627	total: 1.97s	remaining: 3.48s
362:	learn: 0.4602166	total: 1.98s	remaining: 3.47s
363:	learn: 0.4598609	total: 1.98s	remaining: 3.46s
364:	learn: 0.4594705	total: 1.99s	remaining: 3.46s
365:	learn: 0.4591291	total: 1.99s	remaining: 3.45s
366:	learn: 0.4587682	total: 2s	remaining: 3.44s
367:	learn: 0.4583798	total: 2s	remaining: 3.44s
368:	learn: 0.4580162	total: 2.01s	remaining: 3.44s
369:	learn: 0.4576694	total: 2.01s	remaining: 3.43s
370:	learn: 0.4572693	total: 2.02s	remaining: 3.42s
371:	learn: 0.4568886	total: 2.03s	remaining: 3.42s
372:	learn: 0.4565616	total: 2.03s	remaining: 3.41s
373:	learn: 0.4562361	total: 2.04s	remaining: 3.41s
374:	learn: 0.4558890	total: 2.04s	remaining: 3.4s
375:	learn: 0.4555061	total: 2.05s	remaining: 3.4s
376:	learn: 0.4551997	total: 2.05s	remaining: 3.39s
377:	learn: 0.4548827	total: 2.06s	remaining: 3.38s
378:	learn: 0.4544748	total: 2.06s	remaining: 3.38s
379:	learn: 0.4540977	total: 2.07s	remaining: 3.37s
380:	learn: 0.4537318	total: 2.07s	remaining: 3.37s
381:	learn: 0.4533912	total: 2.08s	remaining: 3.36s
382:	learn: 0.4530688	total: 2.08s	remaining: 3.36s
383:	learn: 0.4527880	total: 2.09s	remaining: 3.35s
384:	learn: 0.4524901	total: 2.09s	remaining: 3.35s
385:	learn: 0.4522293	total: 2.1s	remaining: 3.34s
386:	learn: 0.4518809	total: 2.1s	remaining: 3.33s

['catboost_model_updated_Final.joblib']

In [21]:
import joblib
model = joblib.load('catboost_model_updated_Final.joblib')
print(type(model))  # Should be CatBoostClassifier or a pipeline

<class 'catboost.core.CatBoostClassifier'>

In [22]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5222 entries, 3854 to 5555
Data columns (total 34 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Age of the patient                           5222 non-null   int64
 1   Specific gravity of urine                    5222 non-null   float64
 2   Random blood glucose level (mg/dl)           5222 non-null   int64
 3   Blood urea (mg/dl)                           5222 non-null   float64
 4   Serum creatinine (mg/dl)                     5222 non-null   float64
 5   Sodium level (mEq/L)                         5222 non-null   float64
 6   Potassium level (mEq/L)                      5222 non-null   float64
 7   Hemoglobin level (gms)                       5222 non-null   float64
 8   White blood cell count (cells/cumm)          5222 non-null   int64
 9   Red blood cell count (millions/cumm)         5222 non-null   float64
 10  Estimated Glomerular Filtration Rate (eGFR)  5222 non-null   float64
 11  Urine protein-to-creatinine ratio            5222 non-null   float64
 12  Urine output (ml/day)                        5222 non-null   int64
 13  Serum albumin level                          5222 non-null   float64
 14  Parathyroid hormone (PTH) level              5222 non-null   float64
 15  Serum calcium level                          5222 non-null   float64
 16  Duration of hypertension (years)             5222 non-null   int64
 17  Interleukin-6 (IL-6) level                   5222 non-null   float64
 18  Family history of chronic kidney disease     5222 non-null   int64
 19  Serum phosphate level                        5222 non-null   float64
 20  Pus cells in urine                           5222 non-null   int64
 21  Albumin in urine                             5222 non-null   int64
 22  Anemia (yes/no)                              5222 non-null   int64
 23  Creatinine_eGFR_ratio                        5222 non-null   float64
 24  Age_hypertension_ratio                       5222 non-null   float64
 25  Serum_albumin_adjusted                       5222 non-null   float64
 26  total_blood_count                            5222 non-null   float64
 27  blood_creatinine_ratio                       5222 non-null   float64
 28  eGFR_flag                                    5222 non-null   int32
 29  albumin_stress_index                         5222 non-null   float64
 30  hypertension_burden                          5222 non-null   float64
 31  electrolyte_imbalance                        5222 non-null   float64
 32  blood_toxicity_score                         5222 non-null   float64
 33  inflammation_ratio                           5222 non-null   float64
dtypes: float64(24), int32(1), int64(9)
memory usage: 1.4 MB

In [23]:
print(X_train[:5])

      Age of the patient  Specific gravity of urine  \
3854                  45                      1.008
70                    32                      1.018
2111                  60                      1.018
3187                  14                      1.005
1024                  40                      1.008

      Random blood glucose level (mg/dl)  Blood urea (mg/dl)  \
3854                                 135           81.541873
70                                   431           42.766330
2111                                 254          184.374171
3187                                 451          124.377851
1024                                 358          171.167403

      Serum creatinine (mg/dl)  Sodium level (mEq/L)  Potassium level (mEq/L)  \
3854                      1.21            148.682296                 3.915452
70                        6.24            149.593579                 4.112784
2111                      9.61            146.598822                 4.765545
3187                      9.48            124.254465                 3.501349
1024                     13.89            138.594719                 4.558778

      Hemoglobin level (gms)  White blood cell count (cells/cumm)  \
3854                     9.0                                12055
70                      14.9                                 3399
2111                    16.1                                13411
3187                    15.2                                 5147
1024                    13.7                                 6290

      Red blood cell count (millions/cumm)  ...  Age_hypertension_ratio  \
3854                                   5.3  ...                1.800000
70                                     5.8  ...               10.666667
2111                                   5.7  ...                4.615385
3187                                   4.9  ...                0.777778
1024                                   2.5  ...               20.000000

      Serum_albumin_adjusted  total_blood_count  blood_creatinine_ratio  \
3854                0.001118            12060.3               67.389978
70                  0.003720             3404.8                6.853578
2111                0.000733            13416.7               19.185658
3187                0.003098             5151.9               13.120027
1024                0.001366             6292.5               12.323067

      eGFR_flag  albumin_stress_index  hypertension_burden  \
3854          1              0.904977             0.521739
70            0              0.690608             0.060606
2111          0              0.377003             0.196721
3187          1              0.477099             1.133333
1024          0              0.201478             0.024390

      electrolyte_imbalance  blood_toxicity_score  inflammation_ratio
3854             144.766844             49.409124            3.455026
70               145.480795             28.155798            2.818396
2111             141.833277            114.468503            3.915309
3187             120.753116             78.418711            2.028571
1024             134.035941            108.256442            3.598160

[5 rows x 34 columns]

In [24]:
y_train[:5]

3854    0
70      1
2111    1
3187    0
1024    0
Name: Target, dtype: int64

In [25]:
row = X_train.loc[70].tolist()

In [26]:
row

[32.0,
 1.018,
 431.0,
 42.76632975519899,
 6.24,
 149.59357865821312,
 4.112784113586439,
 14.9,
 3399.0,
 5.8,
 80.51,
 3.08,
 870.0,
 3.24,
 19.84426426751941,
 9.11,
 2.0,
 11.95,
 1.0,
 2.89,
 1.0,
 5.0,
 0.0,
 0.07750589988821265,
 10.666666666666666,
 0.003719862227324914,
 3404.8,
 6.853578486410094,
 0.0,
 0.6906077348066298,
 0.06060606060606061,
 145.4807945446267,
 28.155797853119395,
 2.818396226415094]

In [30]:
from sklearn.metrics import classification_report

print(row)
model = joblib.load("catboost_model_updated_Final.joblib")


result = model.predict(row)

result

[32.0, 1.018, 431.0, 42.76632975519899, 6.24, 149.59357865821312, 4.112784113586439, 14.9, 3399.0, 5.8, 80.51, 3.08, 870.0, 3.24, 19.84426426751941, 9.11, 2.0, 11.95, 1.0, 2.89, 1.0, 5.0, 0.0, 0.07750589988821265, 10.666666666666666, 0.003719862227324914, 3404.8, 6.853578486410094, 0.0, 0.6906077348066298, 0.06060606060606061, 145.4807945446267, 28.155797853119395, 2.818396226415094]

1

In [29]:
import joblib

model = joblib.load("catboost_model_updated_Final.joblib")


print("Model expects features in this order:")
print(model.feature_names_)

Model expects features in this order:
['Age of the patient', 'Specific gravity of urine', 'Random blood glucose level (mg/dl)', 'Blood urea (mg/dl)', 'Serum creatinine (mg/dl)', 'Sodium level (mEq/L)', 'Potassium level (mEq/L)', 'Hemoglobin level (gms)', 'White blood cell count (cells/cumm)', 'Red blood cell count (millions/cumm)', 'Estimated Glomerular Filtration Rate (eGFR)', 'Urine protein-to-creatinine ratio', 'Urine output (ml/day)', 'Serum albumin level', 'Parathyroid hormone (PTH) level', 'Serum calcium level', 'Duration of hypertension (years)', 'Interleukin-6 (IL-6) level', 'Family history of chronic kidney disease', 'Serum phosphate level', 'Pus cells in urine', 'Albumin in urine', 'Anemia (yes/no)', 'Creatinine_eGFR_ratio', 'Age_hypertension_ratio', 'Serum_albumin_adjusted', 'total_blood_count', 'blood_creatinine_ratio', 'eGFR_flag', 'albumin_stress_index', 'hypertension_burden', 'electrolyte_imbalance', 'blood_toxicity_score', 'inflammation_ratio']

In [31]:
row = X_train.loc[3854].tolist()

In [32]:
from sklearn.metrics import classification_report

print(row)
model = joblib.load("catboost_model_updated_Final.joblib")


result = model.predict(row)

result

[45.0, 1.008, 135.0, 81.54187330405654, 1.21, 148.68229589100477, 3.9154523289357615, 9.0, 12055.0, 5.3, 24.52, 4.22, 2486.0, 2.78, 33.958987312283284, 9.23, 24.0, 13.06, 1.0, 2.85, 1.0, 2.0, 1.0, 0.04934747145187602, 1.8, 0.0011178126256533975, 12060.3, 67.38997793723681, 1.0, 0.9049773755656109, 0.5217391304347826, 144.766843562069, 49.409123982433925, 3.4550264550264553]

0